### ISSUE TITLE
caching prior data

### ISSUE THREAD

**Issue by awohns** [awohns/tsdate#102]
When caching the prior dataframe, we don't seem to distinguish between a lognormal and a gamma prior. @hyanwong could you take a look at this if you get a chance?

**Comment by hyanwong** [comment]
Do you mean in the `ConditionalCoalescentTimes` class, e.g. the caching in `get_mixture_prior_params()`, or the caching of the `NodeGridValues` object in fill_prior()? If the first, you are right that we simply store alpha, beta. mean, var, so perhaps we should attach an attribute to the returned numpy array that records the distribution that alpha and beta refer to?

What issue is this causing at the moment?

**Comment by hyanwong** [comment]
NB, here's how you might add an attribute like `arr.distr="lognorm"` to an existing numpy array of prior params: https://numpy.org/devdocs/user/basics.subclassing.html#slightly-more-realistic-example-attribute-added-to-existing-array

**Comment by awohns** [comment]
This is in the "prior_1000df.txt" file that we save using np.savetxt on line 204 in date.py. I think it's actually fine as it is since we're saving the expectation and variance of the node under the conditional coalescent, my mistake!
I'll close the issue if you agree

**Comment by hyanwong** [comment]
Yes, I agree. This is before we make the lognorm or gamma approximations. You can close
