### ISSUE TITLE
Running tsdate with num_threads = None and num_threads = 1 yields different results

### ISSUE THREAD

**Issue by awohns** [awohns/tsdate#103]
This seems wrong, any idea what's happening here @hyanwong ? I believe it's in the multiprocessing part that you wrote?

**Comment by hyanwong** [comment]
Yes, that's definitely wrong. It's probably just that line 1220 has normalize in it, but the other branch doesn't. What's the failing test, and I can try to fix it.

**Comment by awohns** [comment]
I noticed it in a CLI test, but that was because the CLI defaulted to num_threads=1 while the python API defaulted to num_threads=None, probably should test they give the same output…
