### ISSUE TITLE
Python API docs missing from readthedocs

### ISSUE THREAD

**Issue by hyanwong** [awohns/tsdate#119]
The python API page on read the docs is not being filled out with method descriptions auto generated from the docstrings in the date.py file

**Comment by awohns** [comment]
Strange, this was working yesterday. I’ll have a look

**Comment by awohns** [comment]
should be fixed now, give it a few minutes for the docs to rebuild

**Comment by awohns** [comment]
Bit confused why this has disappeared with my recent changes, I'll have a look tomorrow

**Comment by awohns** [comment]
Fixed this by adding the module appdirs to docs/requirements.txt. Strange that this happened without any errors either locally when making html in docs or in the readthedocs build page. Have to remember in the future that the docs/requirements.txt can cause this sort of silent error
