### ISSUE TITLE
Handle snipped topologies correctly

### ISSUE THREAD

**Issue by awohns** [awohns/tsdate#129]
tsdate doesn't handle the results of tskit.delete_intervals() or tskit.keep_intervals() correctly.

- spans_by_samples correctly notes when there are 0 nodes fixed at time 0. But build_grid() attempts to add priors when there are 0 nodes fixed at 0.

- We need to check that simply preventing this will solve the problem, with a minimal test example of a snipped topology. 

- Additionally, we should support consistent positional labelling when keep_intervals() has been called without trim()

**Comment by hyanwong** [comment]
We probably don't want to snip out topology, but rather mask it out and skip calculating likelihoods in that region (although we can still calculate a prior for a node with these regions included). See https://github.com/tskit-dev/tsinfer/issues/268 and discussion in https://github.com/tskit-dev/tsinfer/pull/266
