### ISSUE TITLE
Optimise find_node_tip_weights()

### ISSUE THREAD

**Issue by awohns** [awohns/tsdate#42]
tsdate spends ~20% of its time in find_node_tip_weights(). We've determined that this is highly optimisable, specifically, we could use the edge diffs to update the node tip weights instead of iterating over all nodes in every tree. Perhaps we can also avoid checking if the nodes are sample nodes or not, as this is very slow too.

**Comment by hyanwong** [comment]
For info, there is a comment about this in the code at https://github.com/awohns/tsdate/blob/fb381cddf64e89505101fde346d1b9f7d7f5f3c3/tsdate/date.py#L274

**Comment by hyanwong** [comment]
Closed with #54
