### ISSUE TITLE
Do set(ts.samples()) at the top

### ISSUE THREAD

**Issue by hyanwong** [awohns/tsdate#44]
There are a few places we will end up checking if a node is a sample. We should initialise the set once, perhaps globally (or stored within the tsdate object), using `sample_set=set(ts.samples())`) and use it throughout, rather than remake it every time it is needed.

**Comment by hyanwong** [comment]
I'm re-writing the `find_node_tip_weights()` function to be the `__init__()` function of a `FindNodeTips` class, which takes an (optional) `sample_set` param. If this is None, it calculates the sample_set, otherwise it will use the one passed in. That seems like a reasonable way to do this.

**Comment by awohns** [comment]
Sounds great, good idea!

**Comment by hyanwong** [comment]
I've ended up doing quite a lot of code changing (putting things into classes, mainly). I'm in the middle of it now, but it might take a while.
