### ISSUE TITLE
Log Likelihoods

### ISSUE THREAD

**Issue by awohns** [awohns/tsdate#46]
Logging the prior, likelihoods, and forward and backward matrices is significantly less efficient than keeping them unlogged. Specifically, the `np.sum` step in the forward algorithm is significantly slower as a `logsumexp`. It seems to be alright to keep the forward matrix unlogged, but work with logs in the backward matrix... more testing is needed to see if we get underflow errors.

**Comment by awohns** [comment]
I've found that numerical issues can happen when the forwards value gets very small... The solution is probably to use a fast version of log_sum_exp such as discussed in Durbin and here: http://www.nowozin.net/sebastian/blog/streaming-log-sum-exp-computation.html

**Comment by hyanwong** [comment]
We now have a few versions of log_sum_exp in the code, with numba speedups, so I think this can be closed
