### ISSUE TITLE
Speed up get_mixture_prior()

### ISSUE THREAD

**Issue by awohns** [awohns/tsdate#48]
Easy wins for speeding up `get_mixture_prior()`

1. turn inner weights dictionary into numpy array
2. no longer need to run np.array(list(tip_dict.keys()) etc.
3. call, for example `prior_df[500]['Alpha'].values` so you this isn't done under the hood (maybe)
4. `mix_expect` and `mix_var` don't need nodes as a parameter

**Comment by hyanwong** [comment]
Closed with #50 and #51
