### ISSUE TITLE
Investigate numba speedups

### ISSUE THREAD

**Issue by hyanwong** [awohns/tsdate#64]
I forgot to mention, @awohns, that Alistair suggested that you might like to decorate a few of the python routines with `@numba.jit(nopython=True)` (and even maybe with `parallel=True`). Apparently this can lead to huge speedups with little effort. Do you want to investigate?

**Comment by awohns** [comment]
Huge speedups and very little effort sound good to me! I will definitely investigate.

**Comment by awohns** [comment]
I've tried this out with the numpy reduceat step. 
`@numba.vectorize([numba.float64(numba.float64, numba.float64)])
def f(x, y):
    return x + y`
and then
`f.reduceat(vv, matrix_indices.row_based_cols)`

`%%timeit
f.reduceat(np.ones((300000)), np.arange(1000,3000))
861 µs ± 9.11 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)`

`%%timeit
np.add.reduceat(np.ones((300000)), np.arange(1000,3000))
250 µs ± 22.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)`

It seems that numba is much slower?

**Comment by hyanwong** [comment]
I don't think it is aimed at making native numpy operations faster. I think (although I'm no expert) that it's where the existing code is in native python for loops (not numpy methods), and you want it speeding up?

**Comment by hyanwong** [comment]
(I assume `reduceat` is already highly optimised)

**Comment by hyanwong** [comment]
... although having read the docs, I'm not quite sure where would best benefit. Do you want to see if you can grab Alistair over coffee and get some pointers?

**Comment by awohns** [comment]
Good point, I've tried wrapping one of the steps of the forward algorithm in a @numba.jit, but then it complains about not recognizing numpy.add.reduceat... and I've established that using the numba version of reduce at is ~3x slower. 
Yes, I think grabbing Alistair is the best plan here.

For now, the massive speedup that's left is interpolating the likelihood from a table, but perhaps this won't be necessary as discussed.

**Comment by hyanwong** [comment]
Re interpolating likelihoods, I realised that if we have integer spans, we might not have quite so many unique combinations of (span, num_mutations). At least, there are only a limited number of span widths possible for biobank, which is << 0.5 billion. I guess we could estimate this for UKB. In fact, I wonder if it would be interesting to output, as a debug message, the size of the likelihood dictionary that we calculate (vs the number of edges). We could see what it is for the 1000G date inference, perhaps?

**Comment by awohns** [comment]
Good idea, the 1000G inference failed on the last step `return_ts` with `tskit.LibraryError: Times must be finite`, which was the error I told you I saw before.

It also returned `Node not in tree` over 1000 times

**Comment by hyanwong** [comment]
We now have numba in the logsumexp step, so I think this can be closed, as further speed-ups using numba will become obvious.
