### ISSUE TITLE
Issues dating 1000 Genomes

### ISSUE THREAD

**Issue by awohns** [awohns/tsdate#66]
The 1000G inference failed on the last step return_ts with tskit.LibraryError: Times must be finite, which was the error I saw before (and have now replicated).

It also returned Node not in tree over 1000 times

**Comment by hyanwong** [comment]
I solved the previous error (triggered by the code you posted [here](https://github.com/awohns/tsdate/pull/57#issuecomment-560464373)), so unless you are using the old codebase, this is a different bug. Can we triage it somehow?

**Comment by awohns** [comment]
I don't believe it's due to that issue as I'm using the updated codebase (in master). I've added Gil's suggesting of rescaling the likelihoods and this has fixed a smaller example I've found of this issue. I'll try rerunning 1000G with this fix and see if the issue persists.

**Comment by awohns** [comment]
The inference looks like it runs in ~1 hr, but at some point the backward algorithm ends up with Nans. I need to look into it further.

**Comment by awohns** [comment]
Outside maximization runs fine, but outside_pass still has an issue. The problem is that the values at all timepoints in the outside grid underflow quite quickly

**Comment by awohns** [comment]
Solved with #133
