### ISSUE TITLE
Does it matter if the forward log value is -inf

### ISSUE THREAD

**Issue by hyanwong** [awohns/tsdate#70]
You're adding `1e-10` to the forwards values before logging, as some of the original values are zero. But the zeros simply indicate that we never visit that state anyway, so it probably doesn't matter that they become -inf on logging. So is there any reason to add the `1e-10`?

**Comment by awohns** [comment]
I've tried removing this and have run into an issue with the test `test_simple_sim_larger_example` (which I'm really glad was added!). I get nan values in the posterior, and after some digging I've found that the one value in the forward matrix is really small and causes an underflow error leading to a Nan. I've tried keeping everything logged throughout the backward algorithm but the only problem is that I can't find a reduceat function for logsumexp. Not sure how best to proceed here...

**Comment by hyanwong** [comment]
I thought you were normalising though? Doesn’t that deal with the nearly zero value? Even if not, you can probably simply not count up the zero-like values (e.g. remove them before summation etc), if you know they have such a low value, no?

**Comment by hyanwong** [comment]
We can perhaps discuss on Monday now that I have a better grasp of your code?

**Comment by awohns** [comment]
The normalisation doesn't seem to deal with this unfortunately. I'm still trying to get to the bottom of it, I'm not sure how the nans are appearing

**Comment by awohns** [comment]
I think I've sorted it out, another round of normalisation within the forward matrix seems to do the trick

**Comment by awohns** [comment]
Even with the renormalization there seems to still be underflow in some situations. Specifically, in this code, node 1842 has 262 child edges, and I think this will lead to underflow regardless:
`ts = msprime.simulate(sample_size=50, length=2e6, Ne=10000, mutation_rate=1e-8,
                          recombination_rate=1e-8, random_seed=20)

sample_data = tsinfer.formats.SampleData.from_tree_sequence(ts, use_times=False)
start = time.time()
inferred_ts = tsinfer.infer(sample_data)`

 I've done some research and this is alluded to in the following: https://cran.r-project.org/web/packages/seqHMM/vignettes/seqHMM_algorithms.pdf (though they mention the underflow in the backward, not the forward algorithm).  
They propose using log space, but this is less efficient. I'd like to discuss this tomorrow if you're free @hyanwong as I should definitely sort out a reasonable solution before Friday.

**Comment by hyanwong** [comment]
We should find a smaller example where the underflow occurs if we are storing the matrices as 32 bit floats, but where it works if we shift to 64 bit ones. That way we are sure that the underflow is the issue. We can also then test if simply skipping the NaN values (or are they in fact -inf values) gives essentially the same answer.

**Comment by awohns** [comment]
I think I've found the specific issue in the example above.
What actually happens is that the forward val of node 1842 keeps getting more and more restricted as each of its child nodes are visited. Finally, at the edge from 1651 to 1842, the likelihood and the val are disjoint, so we end up getting zero at every time point.

**Comment by awohns** [comment]
A non-ideal solution to the above is to add a very small factor to the "vv" value for each edge. This causes the issue to go away for now

**Comment by hyanwong** [comment]
Can we close this @awohns ?
