### ISSUE TITLE
Turn the forward (and backward) matrix into a class?

### ISSUE THREAD

**Issue by hyanwong** [awohns/tsdate#71]
Instead of having the LowerTriangularMatrix class, which doesn't actually store any data, perhaps we should encapsulate the *entire* forward matrix in a class instead. That way we could put the `reduceat` logic into a class function, and we could also  override the `__getitem__` method so that we can access the nodes to date, without storing the fixed nodes, but while also using  sensible indices.

I can roughly see how this might be done. Should I have a go, or do you want to do it, @awohns?

**Comment by awohns** [comment]
This sounds like a great idea, I’m not sure I totally follow the particulars though... we’d just store the nodes to date as a property of the class?

**Comment by hyanwong** [comment]
I've been hacking on it this evening. I can push the (half-done) code if you want to take a look?

**Comment by hyanwong** [comment]
It's not at all working, but the general gist is in https://github.com/awohns/tsdate/compare/master...hyanwong:lower-tri-class?expand=1

**Comment by hyanwong** [comment]
Closed with #https://github.com/awohns/tsdate/pull/77
