### ISSUE TITLE
Do we need to precompute mutation likelihoods for sample edges?

### ISSUE THREAD

**Issue by hyanwong** [awohns/tsdate#74]
I have a feeling that we only once need to use the likelihood of a *sample edge* (e.g. the array of probs from a sample node `u` at time 0 to its parent at all older timeslices). Is that right? In which case can we skip over the calc in `get_mut_ll()` and just calculate the array when we need it for that node?

**Comment by awohns** [comment]
I believe that’s true… and it might in fact be true for every edge? That’s the way I used to have the code structured, I took the get_mut_ll calculation out to try and simplify the forward algorithm, but it would be better to calculate the likelihood at every step in the forward algorithm to save on memory

**Comment by hyanwong** [comment]
Closing, as https://github.com/awohns/tsdate/pull/81 doesn't cache sample edges. Other edges possibly are worth saving in a cache, as their spans will be shorter, so are less likely to be unique
