### ISSUE TITLE
Backward algorithm only takes information from one branch

### ISSUE THREAD

**Issue by awohns** [awohns/tsdate#76]
A big part of the backward algorithm which is _not_ currently implemented is using information from all the branches where the focal node is a child. Right now the algorithm only uses information from the last edge it sees. 
I'm really surprised we do as well as we do considering this major bug!

**Comment by hyanwong** [comment]
Pasted from email, for reference:

> Just had a chat with Gil (and Rob earlier) about the double counting issue. It seems that geometric scaling by the span of the edge fixes over counting when times are known, but now when we take the integral (sum) over hidden states. 
> 
> Gil proposed a few solutions (gradient descent, looking at individual trees, among others…) or he said if it turns out to be pretty accurate empirically we can justify this as an approximation and move forward.
>

**Comment by hyanwong** [comment]
Now doing geometric scaling.
