### ISSUE TITLE
Cannot recover total functional value of tree

### ISSUE THREAD

**Issue by awohns** [awohns/tsdate#78]
For a single tree, the sum over hidden states for the forward matrix value of the MRCA should be equal to the sum over the hidden states of the posterior at any node.
In a small example (i.e. the n=3 single tree in the utility functions) I can't recover this. I'm unsure if this is a bug or expected due to the way we've set up the HMM.

**Comment by hyanwong** [comment]
Have you taken into account the normalization? You need to multiply by the sum of all the normalizing values, I think.

**Comment by awohns** [comment]
After significant work with Gil, I think we've solved this. Will add tests to ensure that single trees have this property

**Comment by hyanwong** [comment]
This can be closed, can't it @awohns?
