### ISSUE TITLE
Remove the log(x + 1e-10) hack in the upwards pass

### ISSUE THREAD

**Issue by hyanwong** [awohns/tsdate#86]
As discussed with @awohns, this requires checking for `np.exp(-inf - -inf)` in the downwards pass, at  https://github.com/awohns/tsdate/blob/47aa04594a54a673d807d2f011b4291761f6f1ad/tsdate/date.py#L1190

**Comment by hyanwong** [comment]
I'm not sure if https://github.com/awohns/tsdate/issues/70 is also relevant here.

**Comment by awohns** [comment]
I've removed this in my most recent changes, will close issue once PR is merged

**Comment by awohns** [comment]
I've removed this in my most recent changes, will close issue once PR is merged
